{
  "openapi": "3.0.0",
  "info": {
    "title": "Gateway",
    "version": "1.0",
    "license": {
      "name": "Privative"
    },
    "description": "Se describe un servicio para la generación de reportes de transacciones por sitio que permite ser filtrada entre fechas dadas",
    "contact": {
      "name": "Diego Calle",
      "email": "desarrollo@evertecinc.com"
    }
  },
  "servers": [
    {
      "url": "https://test.placetopay.com/rest/gateway",
      "description": "Pruebas"
    }
  ],
  "paths": {
    "/report": {
      "parameters": [],
      "post": {
        "summary": "Solicitar un reporte",
        "operationId": "post-report",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "status": {
                      "$ref": "#/components/schemas/Status"
                    },
                    "id": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "status",
                    "id"
                  ]
                },
                "examples": {
                  "example": {
                    "value": {
                      "status": {
                        "status": "OK",
                        "reason": "00",
                        "message": "La solicitud se ha procesado exitosamente",
                        "date": "2020-01-18T18:00:00-05:00"
                      },
                      "id": 1231
                    }
                  },
                  "error": {
                    "value": {
                      "status": {
                        "status": "FAILED",
                        "reason": "BR",
                        "message": "El reporte solicitado supera los 10 días",
                        "date": "2020-01-18T18:00:00-05:00"
                      },
                      "id": 0
                    }
                  }
                }
              }
            }
          }
        },
        "description": "Permite solicitar que se genere un reporte de transacciones y retorna un identificador para el proceso, el cúal una vez sea llamado el callback puede ser obtenido en el endpoint siguiente",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "",
                "type": "object",
                "properties": {
                  "auth": {
                    "$ref": "#/components/schemas/Authentication"
                  },
                  "filters": {
                    "type": "object",
                    "required": [
                      "startDate",
                      "endDate"
                    ],
                    "properties": {
                      "startDate": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2021-01-10T18:01:27-05:00"
                      },
                      "endDate": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2021-01-12T18:01:27-05:00"
                      }
                    }
                  },
                  "callbackUrl": {
                    "type": "string",
                    "format": "uri"
                  }
                },
                "required": [
                  "auth",
                  "filters"
                ]
              },
              "examples": {
                "example-1": {
                  "value": {
                    "auth": {
                      "login": "string",
                      "tranKey": "string",
                      "nonce": "string",
                      "seed": "2019-08-24T14:15:22Z"
                    },
                    "filters": {
                      "startDate": "2021-01-10T18:01:27-05:00",
                      "endDate": "2019-08-24T14:15:22-05:00"
                    },
                    "compressionFormat": "zip",
                    "callbackUrl": "http://example.com"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/report/obtain": {
      "post": {
        "summary": "Obtener un reporte previamente solicitado",
        "operationId": "post-report-obtain",
        "responses": {
          "200": {
            "description": "OK\n\nUna vez se tiene el reporte retorna la información, el cúal es un archivo separado por comas con los siguientes encabezados\n\n```\nid\ndate\ntransaction_date\nreference\ncurrency_code\namount\ntax\npayment_method\ninternal_reference\nstatus\nreason\nmerchant\nterminal\nauthorization\nrefunded\ninstallments\nlast_digits\nbank_currency\nbank_factor\nbank_amount\nissuer_name\npayer_document\npayer_first_name\npayer_last_name\npayer_email\nip_address\nbatch_number\nline_number\n```",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                },
                "examples": {
                  "example": {
                    "value": "id,date,transaction_date,reference,currency_code,amount,tax,payment_method,internal_reference,status,reason,merchant,terminal,authorization,refunded,installments,last_digits,bank_currency,bank_factor,bank_amount,issuer_name,payer_document,payer_first_name,payer_last_name,payer_email,ip_address,batch_number,line_number\nc42977b5d4ff9d9613320c7ee98e9eb0,2021-01-13T01:54:50-05:00,2021-01-13T01:54:50-05:00,4113943,USD,2327,442.13,ID_VS,221,APPROVED,,000468232,00990101,,,1,0008,USD,1,2327,Testing Bank,32694548,Miss Joanne Fadel MD,Price,blangworth@hotmail.com,237.234.250.30,,\n315c9ca9e64bed46f24a2e18bdd76468,2021-01-13T01:54:50-05:00,2021-01-13T01:54:50-05:00,8122,USD,4457,846.83,ID_VS,222,APPROVED,,000468232,00990101,,,1,0008,USD,1,4457,Testing Bank,44056172,Charlotte Maggio,Steuber,drutherford@gmail.com,164.233.22.247,,\nfd239e99125c326e92137197fd5d1959,2021-01-13T01:54:50-05:00,2021-01-13T01:54:50-05:00,753446151,USD,3798,721.62,ID_VS,223,APPROVED,,000468232,00990101,,,1,0008,USD,1,3798,Testing Bank,51751981,Mr. Abdiel Schroeder DDS,McKenzie,leonard.beier@runte.com,250.136.231.200,,\nbe945b27ff13291409b929cc9cb15274,2021-01-13T01:54:50-05:00,2021-01-13T01:54:50-05:00,482657,USD,1401,266.19,ID_VS,224,APPROVED,,000468232,00990101,,,1,0008,USD,1,1401,Testing Bank,98958097,Dr. Mia Abshire,Douglas,antonia.blanda@wyman.com,32.1.213.30,,\n3aaa74df49cf3634276675c95e49f2af,2021-01-13T01:54:50-05:00,2021-01-13T01:54:50-05:00,77616851,USD,1921,364.99,ID_VS,225,APPROVED,,000468232,00990101,,,1,0008,USD,1,1921,Testing Bank,6211299,Dr. Marcelina Huel I,Considine,vlangworth@emard.biz,249.218.136.4,,\n6e89e692975bb117db78360c8ebf0a00,2021-01-13T01:54:50-05:00,2021-01-13T01:54:50-05:00,74141,USD,773,146.87,ID_VS,226,APPROVED,,000468232,00990101,,,1,0008,USD,1,773,Testing Bank,22736252,Melody Goodwin DDS,Gerlach,iblock@ohara.com,168.87.8.132,,\nb50e4e8cca851a578fa40917030397a3,2021-01-13T01:54:50-05:00,2021-01-13T01:54:50-05:00,828,USD,473,89.87,ID_VS,227,APPROVED,,000468232,00990101,,,1,0008,USD,1,473,Testing Bank,9397147,Freeman Kirlin,Aufderhar,drobel@kshlerin.com,21.185.38.170,,\nb66ffe1bff91a15986cba677bbaeaa7f,2021-01-13T01:54:50-05:00,2021-01-13T01:54:50-05:00,581122,USD,1767,335.73,ID_VS,228,APPROVED,,000468232,00990101,,,1,0008,USD,1,1767,Testing Bank,62818359,Mrs. Rosina Mann,Schaefer,ctremblay@gmail.com,15.8.188.238,,\n135afcb2f872cf55168461e7e874242a,2021-01-13T01:54:50-05:00,2021-01-13T01:54:50-05:00,3896507,USD,7,1.33,ID_VS,229,APPROVED,,000468232,00990101,,,1,0008,USD,1,7,Testing Bank,10597030,Kristy Purdy IV,Mills,clyde68@hotmail.com,148.232.85.97,,\n19868ea1110eca766186806ef0e38f71,2021-01-13T01:54:50-05:00,2021-01-13T01:54:50-05:00,68490,USD,4987,947.53,ID_VS,230,APPROVED,,000468232,00990101,,,1,0008,USD,1,4987,Testing Bank,32385057,Mr. Harley Howe,Rogahn,oreilly.onie@hotmail.com,87.121.113.190,,"
                  }
                }
              }
            }
          },
          "425": {
            "description": "Too Early\n\nCuando la petición se realiza antes de que se termine de generar el reporte",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "properties": {
                    "status": {
                      "$ref": "#/components/schemas/Status"
                    }
                  },
                  "required": [
                    "status"
                  ]
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "description": "",
                "type": "object",
                "properties": {
                  "auth": {
                    "$ref": "#/components/schemas/Authentication"
                  },
                  "id": {
                    "type": "number"
                  }
                },
                "required": [
                  "auth",
                  "id"
                ]
              }
            }
          },
          "description": ""
        },
        "description": "Permite obtener un reporte previamente generado",
        "parameters": [
          {
            "schema": {
              "type": "string",
              "enum": [
                "gzip"
              ]
            },
            "in": "header",
            "name": "accept-encoding",
            "description": "Allows to provide gzip as a compression format"
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "Status": {
        "title": "Status",
        "type": "object",
        "description": "",
        "x-examples": {},
        "properties": {
          "status": {
            "type": "string",
            "description": "",
            "enum": [
              "OK",
              "FAILED",
              "REJECTED",
              "APPROVED"
            ]
          },
          "reason": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "date": {
            "type": "string",
            "format": "date-time"
          }
        },
        "required": [
          "status",
          "reason",
          "message",
          "date"
        ]
      },
      "Authentication": {
        "description": "Maneja la información asociada a la autenticación de la petición actual\n\nTodas las solicitudes al servicio deben ser autenticadas con Web Services Security UsernameToken Profile 1.1.\nhttps://www.oasis-open.org/committees/download.php/13392/wss-v1.1-spec-pr-UsernameTokenProfile-01.htm\n\nUsando PasswordDigest\n```\n(PasswordDigest = Base64 ( SHA-256 ( nonce + seed + tranKey ) ))\n```\n\nEjemplo\n\nPara conectarse con la API REST, la autenticación debe fusionarse como parámetro auth con los datos de la petición.\n```\nlogin = usuarioprueba\nsecretKey = ABCD1234\n```\nDatos generados por el usuario\n\n```\n# Valor aleatorio para cada petición\nnonce = 12345678\n# Fecha ISO 8601 (Y-m-d\\TH:i:s\\Z) or (Y-m-d\\TH:i:sP)\nseed = 2018-01-29T17:02:49-05:00\n```\nTen en cuenta que nonce y seed son generados, login y secretKey son proporcionados por PlacetoPay, con esa información los datos a enviar deben ser:\n\n```\n# Base64(SHA-256(nonce + seed + tranKey))\ntranKey = dsRL5wIymrySr9TgsYtxWZEIb5/RtW1v3n3xLqQZKj4=\n# Base64(Nonce)\nnonce = MTIzNDU2Nzg=\n```\n\nEl valor del trankey resultante es  `Base64(SHA-256(nonce + seed + tranKey))`\n\nEl nonce dentro del SHA-256 no es codificado en Base64, sólo está codificado como parámetro.\n\n",
        "type": "object",
        "properties": {
          "login": {
            "type": "string",
            "minLength": 1
          },
          "tranKey": {
            "type": "string",
            "minLength": 1
          },
          "nonce": {
            "type": "string",
            "minLength": 1
          },
          "seed": {
            "type": "string",
            "minLength": 1,
            "format": "date-time"
          }
        },
        "required": [
          "login",
          "tranKey",
          "nonce",
          "seed"
        ],
        "title": "Authentication",
        "x-examples": {
          "example": {
            "login": "usuarioprueba",
            "tranKey": "dsRL5wIymrySr9TgsYtxWZEIb5/RtW1v3n3xLqQZKj4=",
            "nonce": "MTIzNDU2Nzg=",
            "seed": "2018-01-29T17:02:49-05:00"
          }
        }
      }
    },
    "securitySchemes": {},
    "responses": {}
  }
}