{
  "openapi": "3.0.0",
  "info": {
    "title": "Security",
    "version": "1.0",
    "license": {
      "name": "Privative"
    },
    "description": "Este servicio web y su arquitectura permite a cualquier aplicación conectarse a Placetopay para los servicios de seguridad en el flujo transaccional. independiente del lenguaje de desarrollo.\n\nPara usar el servicio web, deberás tener un lenguaje de programación que pueda comunicarse con un servicio REST.\n\nA continuación se describirán cada uno de los usos y los datos requeridos en la trama para cada uno de los casos.  La respuesta para cada operación está unificada en un solo tipo de trama resultante.",
    "contact": {
      "name": "Diego Calle",
      "email": "desarrollo@evertecinc.com"
    }
  },
  "servers": [
    {
      "url": "https://test.placetopay.com/rest/security",
      "description": "Pruebas Colombia"
    },
    {
      "url": "https://test.placetopay.ec/rest/security",
      "description": "Pruebas Ecuador"
    }
  ],
  "tags": [
    {
      "name": "PinPad",
      "description": "Generación de teclado electrónico"
    }
  ],
  "paths": {
    "/pinpad/transaction": {
      "post": {
        "summary": "Generar transacciones PinPad",
        "operationId": "post-rest-security-transaction",
        "description": "Un PINPAD es un dispositivo electrónico que se utiliza en una transacción de débito, crédito o tarjeta inteligente para aceptar y cifrar el número de identificación personal (PIN) del titular de la tarjeta.\n\nEsta API proporciona un servicio PinPad con generación de PinBlock cifrada según ISO 9564.\n\n",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "auth": {
                    "$ref": "#/components/schemas/Autentication"
                  },
                  "instrument": {
                    "$ref": "#/components/schemas/Instrument"
                  }
                }
              },
              "examples": {
                "Solicitud por tarjeta": {
                  "value": {
                    "auth": {
                      "login": "613822f45568191a8cdf4ad2299f6d23",
                      "tranKey": "bHehjzNcMQVQ1zto0GhmZxjeMhwA+3OlFPbOup16HGc=",
                      "nonce": "NjE1MWQ4MDE5YWViMw==",
                      "seed": "2021-09-27T09:41:05-05:00"
                    },
                    "instrument": {
                      "card": {
                        "number": "4111111111111111"
                      }
                    }
                  }
                },
                "Solicitud por token": {
                  "value": {
                    "auth": {
                      "login": "613822f45568191a8cdf4ad2299f6d23",
                      "tranKey": "bHehjzNcMQVQ1zto0GhmZxjeMhwA+3OlFPbOup16HGc=",
                      "nonce": "NjE1MWQ4MDE5YWViMw==",
                      "seed": "2021-09-27T09:41:05-05:00"
                    },
                    "instrument": {
                      "token": {
                        "token": "4c0886ec949f194f0b535181bb2a707769fd748ff7438d2caab2b0a3e67642a"
                      }
                    }
                  }
                }
              }
            }
          },
          "description": ""
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "$ref": "#/components/schemas/Status"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Data"
                    }
                  }
                },
                "examples": {
                  "Respuesta exitosa": {
                    "value": {
                      "status": {
                        "status": "APPROVED",
                        "reason": "00",
                        "message": "Aprobada",
                        "date": "2021-09-14T17:43:48-05:00"
                      },
                      "data": {
                        "pinPad": {
                          "positions": "7915864032",
                          "transactionId": "b0c62f97-3b06-4c33-b68f-e281e95eb4bb",
                          "pinLength": "4"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Status"
                },
                "examples": {
                  "Error": {
                    "status": {
                      "status": "FAILED",
                      "reason": "0",
                      "message": "",
                      "date": "2021-09-22T16:53:48-05:00"
                    }
                  },
                  "Rejected": {
                    "status": {
                      "status": "REJECTED",
                      "reason": "SU",
                      "message": "El servicio requerido no se encuentra disponible en el sitio",
                      "date": "2021-09-27T09:35:03-05:00"
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "PinPad"
        ]
      },
      "parameters": []
    },
    "/pinpad/pinblock": {
      "post": {
        "summary": "Generar PinBlock en PinPad",
        "operationId": "post-rest-security-pinblock",
        "description": "Permite generar el pinblock con una transaccion en base a las posiciones entregadas por el usuario.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "auth": {
                    "$ref": "#/components/schemas/Autentication"
                  },
                  "instrument": {
                    "$ref": "#/components/schemas/Instrument"
                  }
                }
              },
              "examples": {
                "Solicitud de PinBlock por tarjeta": {
                  "value": {
                    "auth": {
                      "login": "613822f45568191a8cdf4ad2299f6d23",
                      "tranKey": "bHehjzNcMQVQ1zto0GhmZxjeMhwA+3OlFPbOup16HGc=",
                      "nonce": "NjE1MWQ4MDE5YWViMw==",
                      "seed": "2021-09-27T09:41:05-05:00"
                    },
                    "instrument": {
                      "card": {
                        "number": "0215020177972730"
                      },
                      "pinPad": {
                        "transactionId": "b0c62f97-3b06-4c33-b68f-e281e95eb4bb",
                        "positions": "0123"
                      }
                    }
                  }
                },
                "Solicitud de Pinblock por token": {
                  "value": {
                    "auth": {
                      "login": "613822f45568191a8cdf4ad2299f6d23",
                      "tranKey": "bHehjzNcMQVQ1zto0GhmZxjeMhwA+3OlFPbOup16HGc=",
                      "nonce": "NjE1MWQ4MDE5YWViMw==",
                      "seed": "2021-09-27T09:41:05-05:00"
                    },
                    "instrument": {
                      "token": {
                        "token": "4c0886ec949f194f0b535181bb2a707769fd748ff7438d2caab2b0a3e67642a"
                      },
                      "pinPad": {
                        "transactionId": "b0c62f97-3b06-4c33-b68f-e281e95eb4bb",
                        "positions": "0123"
                      }
                    }
                  }
                }
              }
            }
          },
          "description": ""
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "$ref": "#/components/schemas/Status"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Data"
                    }
                  }
                },
                "examples": {
                  "Generación exitosa": {
                    "value": {
                      "status": {
                        "status": "APPROVED",
                        "reason": "00",
                        "message": "Aprobada",
                        "date": "2021-09-14T17:43:48-05:00"
                      },
                      "data": {
                        "pinPad": {
                          "positions": "0123",
                          "transactionId": "b0c62f97-3b06-4c33-b68f-e281e95eb4bb",
                          "pinBlock": "106C56A4819B68EA",
                          "pinLength": "4"
                        }
                      }
                    }
                  }
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "./Gateway.v1.json#/components/schemas/Autentication"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Status"
                },
                "examples": {
                  "Error": {
                    "status": {
                      "status": "FAILED",
                      "reason": "0",
                      "message": "",
                      "date": "2021-09-22T16:53:48-05:00"
                    }
                  },
                  "Rejected": {
                    "status": {
                      "status": "REJECTED",
                      "reason": "SU",
                      "message": "El servicio requerido no se encuentra disponible en el sitio",
                      "date": "2021-09-27T09:35:03-05:00"
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "PinPad"
        ]
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "Autentication": {
        "title": "Autentication",
        "type": "object",
        "properties": {
          "login": {
            "type": "string"
          },
          "tranKey": {
            "type": "string"
          },
          "nonce": {
            "type": "string"
          },
          "seed": {
            "type": "string"
          }
        },
        "description": "Estructura que contiene la información de autenticación del sitio generada de acuerdo al WSSE\nUsernameToken Profile 1.1",
        "x-examples": {}
      },
      "Instrument": {
        "title": "Instrument",
        "type": "object",
        "description": "Estructura que contiene la información acerca del medio de pago a usar en una transacción, esta estructura\nes variable de acuerdo a la solicitud que se genere, cada servicio requiere que se usen unos u otros datos.",
        "properties": {
          "card": {
            "$ref": "#/components/schemas/Card"
          },
          "token": {
            "$ref": "#/components/schemas/Token"
          },
          "pinPad": {
            "$ref": "#/components/schemas/PinPad"
          }
        }
      },
      "Card": {
        "title": "Card",
        "type": "object",
        "description": "Estructura que contiene la información de la tarjeta.",
        "properties": {
          "number": {
            "type": "string"
          }
        }
      },
      "Token": {
        "title": "Token",
        "type": "object",
        "description": "Estructura que contiene la información del token que asocia a la tarjeta\n",
        "properties": {
          "token": {
            "type": "string"
          }
        }
      },
      "Status": {
        "title": "Status",
        "type": "object",
        "properties": {
          "status": {
            "type": "string"
          },
          "reason": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "date": {
            "type": "string"
          }
        },
        "description": "Estructura que contiene la información sobre una solicitud o pago, informa al estado actual de la misma.\n"
      },
      "PinPad": {
        "title": "PinPad",
        "type": "object",
        "description": "Estructura que contiene la información del servicio pinPad",
        "properties": {
          "transactionId": {
            "type": "string"
          },
          "positions": {
            "type": "string"
          },
          "pinBlock": {
            "type": "string"
          },
          "length": {
            "type": "integer"
          }
        }
      },
      "Data": {
        "title": "Data",
        "type": "object",
        "properties": {
          "pinPad": {
            "$ref": "#/components/schemas/PinPad"
          }
        }
      }
    },
    "securitySchemes": {},
    "responses": {}
  }
}